[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'none'; script-src 'none'; object-src 'none'; style-src 'self'; img-src 'none'; media-src 'none'; frame-src 'none'; font-src 'none'; connect-src 'none'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
